steps:
  # build the container images
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'gcr.io/$PROJECT_ID/client', './client']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '-t', 'gcr.io/$PROJECT_ID/leagueofcomrades-client', './client']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '-t', 'gcr.io/$PROJECT_ID/leagueofcomrades-server', './server']

    # push the container images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/leagueofcomrades-client']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/leagueofcomrades-server']

    # Deploy container images to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'leagueofcomrades-client',
        '--image',
        'gcr.io/$PROJECT_ID/leagueofcomrades-client',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--quiet',
        '--allow-unauthenticated',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'leagueofcomrades-server',
        '--image',
        'gcr.io/$PROJECT_ID/leagueofcomrades-server',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--quiet',
        '--allow-unauthenticated',
      ]
images:
  - gcr.io/$PROJECT_ID/leagueofcomrades-client
  - gcr.io/$PROJECT_ID/leagueofcomrades-server
